---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eaglete1/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R bms $DEPLOYPATH
